USE [master]
GO

/****** Object:  Database [ACADEMICO]    Script Date: 28/09/2018 19:49:06 ******/
CREATE DATABASE [ACADEMICO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ACADEMICO', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ACADEMICO.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ACADEMICO_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ACADEMICO_log.ldf' , SIZE = 1040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ACADEMICO] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ACADEMICO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ACADEMICO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ACADEMICO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ACADEMICO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ACADEMICO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ACADEMICO] SET ARITHABORT OFF 
GO

ALTER DATABASE [ACADEMICO] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ACADEMICO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ACADEMICO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ACADEMICO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ACADEMICO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ACADEMICO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ACADEMICO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ACADEMICO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ACADEMICO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ACADEMICO] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ACADEMICO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ACADEMICO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ACADEMICO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ACADEMICO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ACADEMICO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ACADEMICO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ACADEMICO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ACADEMICO] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ACADEMICO] SET  MULTI_USER 
GO

ALTER DATABASE [ACADEMICO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ACADEMICO] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ACADEMICO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ACADEMICO] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ACADEMICO] SET  READ_WRITE 
GO

