/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Classes.Client;
import javax.swing.JOptionPane;

/**
 *
 * @author matheus
 */
public class ViewRegisterClient extends javax.swing.JFrame {
    private Client clients[] = new Client[5];
    private int i = 0;
    
    
    public ViewRegisterClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegisterUser = new javax.swing.JLabel();
        lblRegisterCpf = new javax.swing.JLabel();
        lblRegisterAddress = new javax.swing.JLabel();
        txtRegisterUser = new javax.swing.JTextField();
        txtRegisterAddress = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        lblRegisterSearch = new javax.swing.JLabel();
        btnRegisterSubmit = new javax.swing.JButton();
        btnRegisterShowAll = new javax.swing.JButton();
        txtRegisterSearch = new javax.swing.JTextField();
        txtRegisterCpf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRegisterUser.setText("User:");

        lblRegisterCpf.setText("CPF:");

        lblRegisterAddress.setText("Address:");

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        lblRegisterSearch.setText("Search client:");

        btnRegisterSubmit.setText("Submit");
        btnRegisterSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterSubmitActionPerformed(evt);
            }
        });

        btnRegisterShowAll.setText("Show All Clients");
        btnRegisterShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterShowAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRegisterCpf)
                                    .addComponent(lblRegisterUser)
                                    .addComponent(lblRegisterAddress))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRegisterAddress)
                                    .addComponent(txtRegisterUser)
                                    .addComponent(txtRegisterCpf, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(btnRegisterShowAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRegisterSearch)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRegisterSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegisterSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegisterUser)
                    .addComponent(txtRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegisterCpf)
                    .addComponent(txtRegisterCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegisterAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegisterAddress))
                .addGap(18, 18, 18)
                .addComponent(btnRegister)
                .addGap(18, 18, 18)
                .addComponent(lblRegisterSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegisterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(btnRegisterShowAll)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String clientName = txtRegisterUser.getText();
        String clientCpf = txtRegisterCpf.getText();
        String clientAddress = txtRegisterAddress.getText();        
        
        if(clientName.strip().equals("") || clientCpf.strip().equals("") || clientAddress.strip().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Fields empty!!!", "Error", 2);
        } else {
            clients[i] = new Client(clientName, clientCpf, clientAddress);
            this.i++;
            
            JOptionPane.showMessageDialog(rootPane, "Registered Successfully!!!");

            txtRegisterUser.setText("");
            txtRegisterAddress.setText("");
            txtRegisterCpf.setText("");
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnRegisterSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterSubmitActionPerformed
        String searchName = txtRegisterSearch.getText();
        int j= 0, temp = 0;
        boolean searchOk = false;
        
        if(searchName.strip().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Fields empty!!!", "Error", 2);
        } else {
            while(j < i && !searchOk){
                if(clients[j].getName().equals(searchName)){
                    temp = j;
                    searchOk = true;
                } else {
                    j++;
                }
            }

            if(searchOk){
                JOptionPane.showMessageDialog(rootPane, clients[temp].showSearchData());
            } else {
                JOptionPane.showMessageDialog(rootPane, "No clients found!", "Error", 2);
            }

            txtRegisterSearch.setText("");
        }
    }//GEN-LAST:event_btnRegisterSubmitActionPerformed

    private void btnRegisterShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterShowAllActionPerformed
        String showAll = "<html><h1>Clients</h1><br>";
        
        for(int j = 0; j < i; j++){
            showAll += clients[j].showAllData();
        }        
        
        ViewShowAll objShowAll = new ViewShowAll(showAll, this);
        objShowAll.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegisterShowAllActionPerformed
                         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRegisterClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegisterShowAll;
    private javax.swing.JButton btnRegisterSubmit;
    private javax.swing.JLabel lblRegisterAddress;
    private javax.swing.JLabel lblRegisterCpf;
    private javax.swing.JLabel lblRegisterSearch;
    private javax.swing.JLabel lblRegisterUser;
    private javax.swing.JTextField txtRegisterAddress;
    private javax.swing.JTextField txtRegisterCpf;
    private javax.swing.JTextField txtRegisterSearch;
    private javax.swing.JTextField txtRegisterUser;
    // End of variables declaration//GEN-END:variables
}
